plugins {
    id 'java'
    id 'jacoco'
    id 'checkstyle'
    id("io.qameta.allure") version "3.0.1"
    id 'maven-publish'
    id 'org.springframework.boot' version '4.0.3'
    id 'io.spring.dependency-management' version '1.1.7'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}


group = 'ru.vinhome'
version = "${backend_module_version}"

ext {
    nexusUrl = System.getenv('NEXUS_URL') ?: project.findProperty('nexus_url')
    nexusUsername = System.getenv('NEXUS_USERNAME') ?: project.findProperty('nexus_username')
    nexusPassword = System.getenv('NEXUS_PASSWORD') ?: project.findProperty('nexus_password')
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    maven {
        allowInsecureProtocol = true // будем ходить по http в nexus
        url = "${nexusUrl}/repository/maven-central/" // куда мы идем?

        credentials {
            username nexusUsername
            password nexusPassword
        }
    }

    // maven snapshot
    maven {
        allowInsecureProtocol = true // будем ходить по http в nexus
        url = "${nexusUrl}/repository/maven-snapshots/" // куда мы идем?

        credentials {
            username nexusUsername
            password nexusPassword
        }
    }

    // maven release
    maven {
        allowInsecureProtocol = true // будем ходить по http в nexus
        url = "${nexusUrl}/repository/maven-releases/" // куда мы идем?

        credentials {
            username nexusUsername
            password nexusPassword
        }
    }
}

dependencies {
    implementation ('org.springframework.boot:spring-boot-starter-webmvc') {
        exclude group: "org.springframework.boot", module: "spring-boot-starter-tomcat"
    }
    implementation 'com.zaxxer:HikariCP:7.0.2'
    implementation 'org.springframework.boot:spring-boot-starter-jetty'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation 'org.postgresql:postgresql'

    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation "org.testcontainers:postgresql:${testcontainers_postgresql_version}"
}

jacoco {
    toolVersion = "0.8.13"
}

jacocoTestReport {
    dependsOn test

    reports {
        xml.required.set(true)
        html.required.set(true)
        csv.required.set(false)
    }
}

jacocoTestCoverageVerification {
    dependsOn build
    violationRules {
        {
            rule {
                {
                    limit {
                        minimum = 0.78
                    }
                }
            }
        }
    }
}

checkstyle {
    toolVersion = "10.12.4"
    configFile = file("config/checkstyle/checkstyle.xml")
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java

            group group
            artifactId "${backend_module_name}"
            version version
        }
    }

    repositories {
        maven {
            allowInsecureProtocol = true
            url = version.endsWith("SNAPSHOT")
                    ? "${nexusUrl}/repository/maven-snapshots/"
                    : "${nexusUrl}/repository/maven-releases/"
            credentials {
                username = nexusUsername
                password = nexusPassword
            }
        }
    }
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport, jacocoTestCoverageVerification, javadoc
}